import { defineCompatAsyncComponent } from '../modules/vue-async-component'

export const adminRoutes = [
  { path: '/', redirect: '/dashboard' },
  { path: '/dashboard', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-dashboard.vue')) },
  { path: '/general', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-general.vue')) },
  { path: '/locale', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-locale.vue')) },
  { path: '/navigation', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-navigation.vue')) },
  { path: '/pages', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-pages.vue')) },
  { path: '/pages/:id(\\d+)', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-pages-edit.vue')) },
  { path: '/pages/visualize', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-pages-visualize.vue')) },
  { path: '/tags', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-tags.vue')) },
  { path: '/theme', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-theme.vue')) },
  { path: '/groups', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-groups.vue')) },
  { path: '/groups/:id(\\d+)', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-groups-edit.vue')) },
  { path: '/users', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-users.vue')) },
  { path: '/users/:id(\\d+)', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-users-edit.vue')) },
  { path: '/analytics', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-analytics.vue')) },
  { path: '/auth', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-auth.vue')) },
  { path: '/comments', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-comments.vue')) },
  { path: '/rendering', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-rendering.vue')) },
  { path: '/editor', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-editor.vue')) },
  { path: '/extensions', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-extensions.vue')) },
  { path: '/logging', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-logging.vue')) },
  { path: '/search', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-search.vue')) },
  { path: '/storage', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-storage.vue')) },
  { path: '/api', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-api.vue')) },
  { path: '/mail', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-mail.vue')) },
  { path: '/security', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-security.vue')) },
  { path: '/ssl', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-ssl.vue')) },
  { path: '/system', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-system.vue')) },
  { path: '/utilities', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-utilities.vue')) },
  { path: '/webhooks', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-webhooks.vue')) },
  { path: '/dev-flags', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin-dev" */ '../components/admin/admin-dev-flags.vue')) },
  { path: '/contribute', component: defineCompatAsyncComponent(() => import(/* webpackChunkName: "admin" */ '../components/admin/admin-contribute.vue')) }
]
